version: '2'

services:

  bibliomap-enricher:
    container_name: bibliomap-enricher
    image: node:6.9.1
    volumes:
      - .:/app
    working_dir: /app
    environment:
      http_proxy:  ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
      NODE_ENV: "development"
      DEBUG: ${DEBUG}
      BBE_EZPAARSE_URL: "http://ezpaarse:59599"
      BBE_EZPAARSE_PREDEF: "00-fr-istex"
      BBE_LISTEN_HARVESTER_HOST: "0.0.0.0"
      BBE_LISTEN_HARVESTER_PORT: 27777
      BBE_BROADCAST_VIEWER_HOST: "bibliomap-viewer"
      BBE_BROADCAST_VIEWER_PORT: 27779
    tty: true         # to have nice debug(...) outputs
    stdin_open: true  # to be able to use CTRL+C to stop the debug
    command: npm start
