version: '2'

services:

  ezpaarse2log.io:
    container_name: ezpaarse2log.io
    image: ezpaarseproject/ezpaarse2log.io:1.0.1
    environment:
      NODE_ENV: "production"
      DEBUG: ${DEBUG}
    working_dir: /app
    tty: true         # to have nice debug(...) outputs
    stdin_open: true  # to be able to use CTRL+C to stop the debug
    # Restarts when the host server reboot
    # or if the nodejs process crashes. NodeJS crashe
    # appends at first startup because it needs time for mongodb
    # to initialize. (this option replaces the usual forever or pm2 stuff)
    restart: unless-stopped
